services:
  pgdatabase:
    image: postgres:13
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ny_taxi
    volumes:
      - "./ny_taxi_postgres_data:/var/lib/postgresql/data:rw"
    ports:
      - "5432:5432"
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    volumes:
      - "./pgadmin:/var/lib/pgadmin"
    ports:
      - "8080:80"
  ingestion:
    image: taxi_ingest:latest
    depends_on:
      - pgdatabase
    command:
      - --user=root
      - --password=root
      - --host=pgdatabase
      - --port=5432
      - --db=ny_taxi
      - --table_name=green_tripdata_trip
      - --url=https://github.com/DataTalksClub/nyc-tlc-data/releases/download/green/green_tripdata_2019-01.csv.gz
      - --date-column=lpep_pickup_datetime
      - --date-column=lpep_dropoff_datetime
